### ISSUE TITLE
Widget support for android

### ISSUE THREAD

**Issue by dp-7** [Konyaco/CollinsDictionary#11]
I think it's a good option to add widget support to this application on android.

**Comment by Konyaco** [comment]
Due to the limitations of Andoird, it's unable to use TextInput in widgets. The only thing you can do is handle tapping/slipping gestures and display information. As a result, widget can not provide the basic functionality. If we just put a fake input area in the widget, and launch the application when you click it, it's not more convenient than just launching the app.🤔 If you have better ideas, welcome to suggest. ✌️
